config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :users, controllers: { :sessions => "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"}

  # devise_scope :users do
  #   get "sign_out", :to => "devise/sessions#destroy"
  # end

  resources :users do
    resources :reviews
  end

  resources :messages
  resources :playdates
  resources :events
  resources :user_matches

  get '/', to: 'events#home', as: :home
  get 'users/:id/questionnaire', to: 'users#questionnaire', as: :questionnaire
  get '/suggestmedates', to: 'playdates#suggest', as: :suggest
  get '/getmedates', to: 'playdates#searchdates', as: :searchdates
  put 'users/:id/update_preferences', to: 'users#update_preferences', as: :update_preferences

  put 'users/:id/create_match', to: 'users#create_match', as: :create_match

  put 'user_matches/:id/accept_match', to: 'user_matches#accept_match', as: :accept_match
  put 'user_matches/:id/reject_match', to: 'user_matches#reject_match', as: :reject_match

  get 'events/:id/like_event', to: 'events#like_event', as: :like_event

  get 'events/:id/dislike_event', to: 'events#dislike_event', as: :dislike_event

  root 'events#home'

end

app/models/playdate.rb
class Playdate < ActiveRecord::Base
  # ASSOCIATIONS #
  has_and_belongs_to_many :users
end

app/controllers/playdates_controller.rb
class PlaydatesController < ApplicationController
  
  def index
    @playdates = Playdate.all
  end

  def new
    @playdate = Playdate.new
  end

  def create
    name = params[:playdate][:dog2_id]
    user = User.where(dog_name:name)[0]
    user_id = user.id
    @playdate = Playdate.new(playdate_params)
    @playdate.dog2_id = user
    @playdate.save
    if @playdate.save
      redirect_to playdates_path
      flash[:notice] = "You successfully created a playdate!"
    else
      # redirect_to playdate form
    end
    binding.pry
  end

  def edit
    @playdate = Playdate.find(params[:id])
  end

  def update
    @playdate = Playdate.find(params[:id])
    if @playdate.update(playdate_params)
      # redirect_to playdatse_path
      flash[:notice] = "You successfully updated a playdate!"
    else
      render 'new'
    end
  end

  def show
    @playdate = Playdate.find(params[:id])
  end
  
  def destroy
    @playdate = Playdate.find(params[:id])
    @playdate.destroy
    # redirect_to 
    flash[:notice] = "You successfully deleted a playdate!"
  end

  def suggest
    @users = User.all
  end

  private
  def playdate_params
    params.require(:playdate).permit(:dog1_id, :dog2_id, :name, :date, :place, :description)
  end

end

app/helpers/playdates_helper.rb
module PlaydatesHelper
end

app/views/playdates/_playdateform.html.haml
.form
  .playdate-form
    =minimal_form_for @playdate do |f|
      %p= f.hidden_field :dog1_id, :value => current_user.id 

      %p Date Name
      %input#dog2-name{:type => "text", :name => "playdate[dog2_id]"} 

      %p= f.input :name, wrapper_html: { class: 'playdate-name' }, required: true, placeholder: 'name your playdate!'

      %p= f.input :description, wrapper_html: { class: 'playdate-description' }, placeholder: 'what are you dogs gonna do?'
      %p Date
      %p= f.input :date, wrapper_html: { class: 'playdate-date' }, required: true, as: :date, start_year:Date.today.year, end_year: Date.today.year + 2, discard_day: false, order: [:day, :month, :year]

      %p= f.input :place, wrapper_html: { class: 'playdate-place' }, required: true, placeholder: 'meet-up location'
      %p Time
      %p= f.input :time, wrapper_html: { class: 'playdate-time' }, required: true

      .submit
      %p= f.button :submit, "Create Playdate", class: "submit-button"

app/views/playdates/_suggestbypref.html.haml
.suggest-by-preference
  %p You want these qualities in your date:
  - current_user.preference_list.each do |pref|
    =pref
  %p You are highly matched with these hot dogs: 
  - high_matches =  User.tagged_with(current_user.preference_list, :match_all => true)
  - high_matches.each do |highmatch|
    - unless highmatch.dog_name == current_user.dog_name
      %p= link_to(highmatch.dog_name, user_path(highmatch))

-# .search-by
-#   %button Male
-#   %button Female

-# - User.tagged_with(["#{}"], :match_all => true)
-# - User.tagged_with(["#{}"], :any => true)
-# - User.tagged_with(["#{}"], :exclude => true)

-# -User.where(gender:"male").each do |male|
-#   =male.dog_name
-# -User.where(gender:"female").each do |female|
-# -User.where(breed:"#{}").each do |female|
-# -User.where(neutered:true).each do |neutered|
-# -User.where(neutered:false).each do |unneutered|
-# -User.where(neutered:false).each do |unneutered|
-# -User.where(dog_age>5).each do |young|
-# -User.where(5<dog_age<10).each do |middle|
-# -User.where(dog_age>10).each do |old|

app/views/playdates/edit.html.haml
%h2 Edit Playdate
= render 'playdateform'

app/views/playdates/home.html.haml
%h1 Homepage

app/views/playdates/index.html.haml
.index-page
  %h2 My Playdates
  = current_user.owner_name
  and
  = current_user.dog_name
  Playdates

  - @user_playdates = current_user.playdates 
  - @user_playdates.each do |playdate|
    %p= playdate.name
    %p= playdate.description
    %p= playdate.date
    %p= playdate.time
    %p= playdate.location
    %p= link_to(playdate.name, playdate_path(playdate))

#map-canvas

:javascript
  function initialize(){
    var myLatLng = new google.maps.LatLng(51.5361, -0.1751)
    var mapCanvas = document.getElementById('map-canvas');
    var mapOptions = {
      center: myLatLng,
      zoom: 16,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    map = new google.maps.Map(mapCanvas, mapOptions);
    addMarker(map);

    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map
    });

  }


  function addMarker(map_one) {
   if(navigator.geolocation){
     navigator.geolocation.getCurrentPosition(function(position){
       var pos = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
       console.log(pos);

       var infowindow = new google.maps.InfoWindow({
         map: map_one,
         position: pos,
         content: "You are here WOOF!"
       });


       var request = {
        location: pos,
        radius: '500',
        types: ['park']
      };
      service = new google.maps.places.PlacesService(map);
      service.nearbySearch(request, callback);

      map_one.setCenter(pos);
    }, function() {
     handleNoGeolocation(true);
   });
   } else {
     handleNoGeolocation(false);
   }
  }

  function handleNoGeolocation(errorFlag) {
   if (errorFlag) {
     var content = 'error: geolocation server failed';
   } else {
     var content = 'error: your browser does not support geolocation';
   }

   var infowindow = new google.maps.InfoWindow(options);
   map.setCenter(options.position);

  }

  function callback(results, status) {
   if (status == google.maps.places.PlacesServiceStatus.OK) {
     for (var i = 0; i < results.length; i++) {
       var place = results[i];
       createMarker(results[i]);
     }
   }
  }

  function createMarker(place) {
   var placeLoc = place.geometry.location;
   var marker = new google.maps.Marker({
     map: map,
     position: place.geometry.location
   });
  }


  google.maps.event.addDomListener(window, 'load', initialize);
  

app/views/playdates/new.html.haml
%h2 New Playdate
= render 'playdateform'

app/views/playdates/show.html.haml
%h2= @playdate.name
%p= @playdate.description
%p= @playdate.date
%p= @playdate.time
%p= @playdate.location

%p= link_to('Edit', edit_playdate_path(@playdate))
%p= link_to('Delete', playdate_path(@playdate), method: :delete)
%p= link_to('Add New Event', new_playdate_path)

app/views/playdates/suggest.html.haml
%h1 put suggested dates here


= render 'playdates/suggestbypref'