config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :users, controllers: { :sessions => "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"}

  # devise_scope :users do
  #   get "sign_out", :to => "devise/sessions#destroy"
  # end

  resources :users do
    resources :reviews
  end

  resources :messages
  resources :playdates
  resources :events
  resources :user_matches

  get '/', to: 'events#home', as: :home
  get 'users/:id/questionnaire', to: 'users#questionnaire', as: :questionnaire
  get '/suggestmedates', to: 'playdates#suggest', as: :suggest
  get '/getmedates', to: 'playdates#searchdates', as: :searchdates
  put 'users/:id/update_preferences', to: 'users#update_preferences', as: :update_preferences

  put 'users/:id/create_match', to: 'users#create_match', as: :create_match

  put 'user_matches/:id/accept_match', to: 'user_matches#accept_match', as: :accept_match
  put 'user_matches/:id/reject_match', to: 'user_matches#reject_match', as: :reject_match

  get 'events/:id/like_event', to: 'events#like_event', as: :like_event

  get 'events/:id/dislike_event', to: 'events#dislike_event', as: :dislike_event

  root 'events#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # DEVISE #
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  # GRAVATASTIC #
  include Gravtastic
  gravtastic :default => "wavatar", :size => 400

  # MOUNTING UPLOADER
  mount_uploader :dog_picture, UserImageUploader
  mount_uploader :owner_picture, UserImageUploader
  # mount_uploader :avatar, AvatarUploader

  # ASSOCIATIONS #
  has_and_belongs_to_many :events
  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :playdates, dependent: :destroy
  has_many :user_matches, :foreign_key => :dog_requester_id
  has_many :users, :through => :user_matches, :source => :dog_requestee
  has_many(:user_matches, :foreign_key => :dog_requester_id, :dependent => :destroy)
  has_many(:reverse_user_matches, :class_name => :UserMatch, :foreign_key => :dog_requestee_id, :dependent => :destroy)

  # has_many :users, :through => :user_matches, :source => :dog_requestee

  has_many :messages, through: :user_matches 

  # TAGGABLE #

  acts_as_taggable
  acts_as_taggable_on :preferences

  # OMNIAUTH #

  # RATABLE #
  letsrate_rater
  letsrate_rateable "user_rating"

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.owner_name = auth.info.name   # assuming the user model has a name
      user.owner_picture = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_filter :configure_permitted_parameters, :only => [:create]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :dog_name, :owner_name, :dog_age, :dog_bio, :owner_bio, :gender, :breed, :neutered, :address, :interest, :user_rating, :dog_picture, :owner_picture) }
  end

  def after_sign_up_path_for(resource)
    '/users/questionnaire'
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all 
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update
  end

  def update_preferences
    preferences = params[:user]
    current_user.preference_list.add(preferences)
    current_user.save
  end

  def create_match
    match_fields = params[:user]
    # param_dog_requester = match_fields[0] 
    # param_dog_requestee = match_fields[1] 
    param_dog_requester_id = match_fields[2]
    param_dog_requestee_id = match_fields[3]
    @match = UserMatch.create(
      dog_requester_id: param_dog_requester_id,
      dog_requestee_id: param_dog_requestee_id,
      status: "pending"
      )
    render json: @match 
  end


  def questionnaire
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:id, :dog_name, :owner_name, :dog_age, :dog_bio, :owner_bio, :gender, :breed, :neutered, :address, :user_rating, :dog_picture, :owner_picture, :preference_list => [])
  end

  def user_match_params
    params.require(:user_matches).permit(:id, :dog_requester_id, :dog_requestee_id)
  end
end

app/views/users/_questionnaire.html.haml
.questionnaire 
  %h2 let's find you your perfect date
  #questionnaire
    %p.title Male or Female?
    %input.qn{:type=>"radio", :name => 'gender', :value => 'male'}Male 
    %input.qn{:type=>"radio", :name => 'gender', :value => 'female'}Female 
    %input.qn{:type=>"radio", :name => 'gender', :value => 'both'}Both 

    %p.title Neutered/ spayed - yay or nay?
    %input.qn{:type=>"radio", :name => 'neutered', :value => 'neutered'}Yes
    %input.qn{:type=>"radio", :name => 'neutered', :value => 'unneutered'}Nope

    %p.title When are you usually free?
    %input.qn{:type=>"checkbox", :name => 'availability', :value => 'weekday-evening'}Weekday Evenings
    %input.qn{:type=>"checkbox", :name => 'availability', :value => 'weekday-daytime'}Weekday Daytime
    %input.qn{:type=>"checkbox", :name => 'availability', :value => 'weekends'}Weekends

    %p.title Kind'ov doggy activities?
    %input.qn{:type=>"checkbox", :name => 'activity', :value => 'indoor'}Indoor
    %input.qn{:type=>"checkbox", :name => 'activity', :value => 'outdoor'}Outdoor

    %p
      %button.btn.btn-default.btn-lg#qn-submit Date Me

app/views/users/index.html.haml
-# List All Users #
-# update this page to a search/ suggest users functionality #
- @users.each do |user|
  = link_to(user.email, user_path(user))

app/views/users/message.html.haml
#chatarea
  #messagesbox
    %ul#messages
  %input#inputbox
  %button.send
    Send

app/views/users/questionnaire.html.haml
= render 'questionnaire'

app/views/users/show.html.haml
- if @user.user_matches.length > 0
  -if current_user.id != @user.id
    -user_match_id1 = UserMatch.where(dog_requester_id:current_user.id, dog_requestee_id:@user.id)[0]
    -user_match_id2 = UserMatch.where(dog_requestee_id:current_user.id, dog_requester_id:@user.id)[0]
    - if user_match_id2 === nil
      =link_to('Chat', user_match_path(user_match_id1.id))
    - else
      =link_to('Chat', user_match_path(user_match_id2.id))

.dog-block
  %h3 DOG DETAILS
  %p#dog-name 
    %strong Name of Dog:
    = @user.dog_name 
    %br/
    = image_tag @user.dog_picture.detail.url
  %br/

  %p#dog-age.dog 
    %strong Age of Dog:
    = @user.dog_age
  %br/

  %p.dog 
    %strong Dog's Bio:
  %p.dog Puppy kitty ipsum dolor sit good dog swimming meow rover vaccine chew wagging critters fish leash feeder barky foot. Vaccine heel wet nose vitamins feathers window fleas food Scooby snacks bark parrot meow wet nose slobber toys Spike slobbery barky. Aquatic throw roll over teeth gimme five tooth toys good boy run fetch run fast tuxedo lazy dog brush fur chow. Fetch finch water dog birds dog house speak ferret purr harness. Tigger throw puppy tooth lick scratch dragging stick bark food. Kitten run swimming walk heel run fast roll over gimme five drool tabby teeth dinnertime walk leash pet food smooshy pet toys. Behavior Spike parakeet dinnertime yawn licks grooming play dead parrot roll over. Walk smooshy cockatiel catch cage purr Mittens paws collar. Polydactyl harness fish smooshy pet supplies biscuit slobber furry good boy.Heel collar slobber gimme five polydactyl stay barky lazy cat pet. Scratch warm pet gate lazy cat drool scratcher tooth fetch tabby carrier groom Fido. 
  %br/

  %p.dog 
    %strong Gender of Dog:
    = @user.gender 
  %br/

  %p.dog 
    %strong Breed of Dog:
    = @user.breed
  %br/

  %p.dog
    %strong Neutered Status:
    = @user.neutered 
  %br/

.owner-block
  %h3 OWNER DETAILS
  %p#owner-name.owner
    %strong Name of Owner:
    = @user.owner_name
    %br/
  -if @user.owner_picture.length < 5 
    =image_tag @user.gravatar_url
  -else 
    = image_tag @user.owner_picture.detail.url

  %p.owner 
    %strong Owner's Bio:
  %p.owner Attitude is everything. Jeans represent democracy in fashion. The difference between style and fashion is quality. I think there is something about luxury - it's not something people need, but it's what they want. It really pulls at their heart. Fashion can be this mysterious thing that you can't explain.  

  %p.owner 
    %strong Email Address:
    = @user.email
  %br/

  %p
    %strong Residential Address:
  %address#address
    = @user.address  

  -# Google Maps #
  %p#map-canvas

.buddy-block
  -# Add Buddy Button #
  -if @user.id != current_user.id
    %button#add-buddy-button{:data => {:dog_requester_id => current_user.id, :dog_requester => current_user, :dog_requestee_id => @user.id, :dog_requestee => @user}}
      %span.buddy-status Add Buddy
      %span.buddy-status.hide Buddy Requested

  -if @user.id === current_user.id
    .buddies
      %p Your buddies are:
      - current_user.user_matches.each do |buddy|
        - buds = User.where(id:buddy.dog_requestee_id)



  %p Your buddy requests:
  - current_user.reverse_user_matches.each do |match|
    -if match.dog_requestee_id == current_user.id
      %p= User.find(match.dog_requester_id).dog_name
    -if match.status == "pending"
      %button#accept-request{:data => {:id => match.id}} Accept
      %button#reject-request Reject
    -else
      %button#delete-buddy Delete Buddy

  %p The buddies you have requested:
  - current_user.user_matches.each do |match|
    -if match.dog_requester_id == current_user.id
      %p= User.find(match.dog_requestee_id).dog_name
    -if match.status == "pending"
      %button#pending Pending
    -else
      %button#accepted Accepted

:javascript

  var geocoder;
  var map;
  function initialize() {


    geocoder = new google.maps.Geocoder();

    var latlng = new google.maps.LatLng(51.519889, -0.068799);
    var mapOptions = {
      zoom: 16,
      center: latlng
    }
    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    codeAddress();
  }

  function codeAddress() {
    var address = $('#address').text();
    if (address) {
      geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          map.setCenter(results[0].geometry.location);
          var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
          });
        } else {
          alert('Geocode was not successful for the following reason: ' + status);
        }
      });
      
    };
  }

  google.maps.event.addDomListener(window, 'load', initialize);