config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :users, controllers: { :sessions => "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"}

  # devise_scope :users do
  #   get "sign_out", :to => "devise/sessions#destroy"
  # end

  resources :users do
    resources :reviews
  end

  resources :messages
  resources :playdates
  resources :events
  resources :user_matches

  get '/', to: 'events#home', as: :home
  get 'users/:id/questionnaire', to: 'users#questionnaire', as: :questionnaire
  get '/suggestmedates', to: 'playdates#suggest', as: :suggest
  get '/getmedates', to: 'playdates#searchdates', as: :searchdates
  put 'users/:id/update_preferences', to: 'users#update_preferences', as: :update_preferences

  put 'users/:id/create_match', to: 'users#create_match', as: :create_match

  put 'user_matches/:id/accept_match', to: 'user_matches#accept_match', as: :accept_match
  put 'user_matches/:id/reject_match', to: 'user_matches#reject_match', as: :reject_match

  get 'events/:id/like_event', to: 'events#like_event', as: :like_event

  get 'events/:id/dislike_event', to: 'events#dislike_event', as: :dislike_event

  root 'events#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
  # ASSOCIATIONS #
  has_and_belongs_to_many :users

  # VOTABLE GEM #
  acts_as_votable
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    if @event.save
      redirect_to events_path
      flash[:notice] = "You successfully created an event!"
    else
      # render 'newevent'
      flash[:notice] = "Something went wrong in the creation of your event, try again!"
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
      flash[:notice] = "You successfully updated an event!"
    else
      # render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end
  
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
    flash[:notice] = "You successfully deleted an event!"
  end

  def like_event
    @event = Event.find(params[:id])
    @event.liked_by current_user
    @event.save
    render json: @event
  end

  def dislike_event
    @event = Event.find(params[:id])
    @event.unliked_by current_user
    @event.save
    render json: @event
  end

  private
  def event_params
    params.require(:event).permit(:name, :date, :place, :time, :event_rating)
  end

end
  

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_eventform.html.haml
.form
  .event-form
    =form_for @event do |f|
      %p= f.label :name
      %p= f.text_field :name

      %p= f.label :date
      %p= f.text_field :date

      %p= f.label :place
      %p= f.text_field :place

      %p= f.label :time
      %p= f.text_field :time

      %p= f.label :event_rating
      %p= f.text_field :event_rating

      .submit
      %p= f.button :submit

app/views/events/edit.html.haml
%h2 Edit Events

= render 'form'

app/views/events/home.html.haml
- if user_signed_in? === false
  #about-us
    %section.window#1
      %p#hotdogs Hotdogs
      %p.tag-line Doggy Dating App
      = render :partial => 'layouts/register'
    %section.window#2
      %h2#window-two-text about us
      %p Whether you are looking to: find another dog to join yours in the park, find an answer to a question, or simply share your thoughts on pet ownership, you will find it here!
      
    %section.window#3
      %h2 tailor
      %p Set up your profile for optimum dog to dog matching! Customize your experience!
    %section.window#4
      %h2 match
      %p Choose from a selection of an array of little pups and filter by characteristics. Or pick from one of our hand-generated matches!
    %section.window#5
      %h2 date
      %p Propose a date with your newly-matched buddy! He or she may just be the mustard to your hotdog, your ketchup to your bun.

    %section.window#6
      %h2 community
      %p Join doggie events to socialize with our Hotdogs. Better yet, organize your own!
    %section.window#7
      %h2 join the puppies!
      %p Have security in others! Encourages humane treatment of pets and people alike.
      %p= render :partial => 'layouts/register'

app/views/events/index.html.haml
.index-page
  %h2 join our community
  - @events.each do |event|
    .indiv-event
      %p= link_to(event.name.downcase, event_path(event))
      .event-place.place-hide=event.place.upcase

app/views/events/new.html.haml
%h2 New Event

= render 'eventform'

app/views/events/show.html.haml
%h2= @event.name

%p= "This event takes place in #{@event.place}. This event is rated a #{@event.event_rating} star event."

- if @event.organizer_id === current_user.id
  %p= link_to('Edit', edit_event_path(@event))
  %p= link_to('Delete', event_path(@event), method: :delete)



%button#like{value: @event.id} Like

-likes = @event.get_likes.size 
#like-size=likes

%button#dislike Dislike

- dislikes = @event.get_downvotes.size
#dislike-size=dislikes