config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :users, controllers: { :sessions => "users/sessions", :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations"}

  # devise_scope :users do
  #   get "sign_out", :to => "devise/sessions#destroy"
  # end

  resources :users do
    resources :reviews
  end

  resources :messages
  resources :playdates
  resources :events
  resources :user_matches

  get '/', to: 'events#home', as: :home
  get 'users/:id/questionnaire', to: 'users#questionnaire', as: :questionnaire
  get '/suggestmedates', to: 'playdates#suggest', as: :suggest
  get '/getmedates', to: 'playdates#searchdates', as: :searchdates
  put 'users/:id/update_preferences', to: 'users#update_preferences', as: :update_preferences

  put 'users/:id/create_match', to: 'users#create_match', as: :create_match

  put 'user_matches/:id/accept_match', to: 'user_matches#accept_match', as: :accept_match
  put 'user_matches/:id/reject_match', to: 'user_matches#reject_match', as: :reject_match

  get 'events/:id/like_event', to: 'events#like_event', as: :like_event

  get 'events/:id/dislike_event', to: 'events#dislike_event', as: :dislike_event

  root 'events#home'

end

app/views/layouts/_nav.html.haml
-# NAVIGATION BAR
-# only visible to logged in users
.nav 
  =link_to('All My Playdates', playdates_path)
  =link_to('All Events', events_path)
  =link_to('New Playdate', new_playdate_path)
  = link_to('New Event', new_event_path)

  =link_to('Profile', user_path(current_user))

  =link_to('Suggest Dates', suggest_path)

  =link_to('Logout', destroy_user_session_path, :method => :delete)

  =link_to('Edit registration', edit_user_registration_path)

app/views/layouts/_register.html.haml
-# SIGNIN/ LOGIN LINKS
.registration
  %button.btn.btn-default.btn-lg
    = link_to('login', new_user_session_path)
  %button.btn.btn-default.btn-lg
    = link_to('register', new_user_registration_path)

  %div#blank-space

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HotdogsApp
    = stylesheet_link_tag 'application', media: 'all'


    %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyA00iEetE8yy2uZY4ejEskfM6zypsXnhps&libraries=places"}
    <link href='https://fonts.googleapis.com/css?family=Raleway:500,800,700,900,400' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Dosis:400,500' rel='stylesheet' type='text/css'>
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body

    %p.notice= notice
    -# %p.alert= alert

    - if user_signed_in?
      .nav
        %p= render 'layouts/nav'

    = yield